= Протокол обмена с весами ВКТ-4 (св 8)

. Скорость обмена 4800, 9600
. Без паритета
. 8 бит, один стоп бит

Структура пакета:



.Запрос:
|===
| 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9
|Синхробайт|Длина пакета без КС|Адрес весов|Адрес ведущего ус-ва|Комманда|Адрес переменной 3+|Данные|Контрольная сумма (КС)
|0x54|0х08|ХХ|YY|1|АА|0|0|0|КК
|===

.Ответ:
|===
| 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9
|Синхробайт|Длина пакета без КС|Адрес ведущего ус-ва|Адрес весов|Комманда|Адрес переменной 3+|Данные |Контрольная сумма (КС)
|0x54|0х08|YY|ХХ|1|АА ||||КК
|===


Комманда: 1-чтение.

Адрес переменной для весов версии 1:

* 0х60 – Накопление
* 0х5d – Производительность

Адрес переменной для весов версии 2:

* 0x60 - Накопление
* 0x63 - Производительность усреденная (отображаемая на дисплее)
* 0x44 - Производительность мгновенная
* 0x37 - Производительность с коротким усреднением

Декодирование данных накопления: 3 байта. Результат возвращает в символьном виде: первая цифра полубайт 6-го байта.
Пример кода для декодирования накопления:
```
    int32_t accum = 0;
    accum += buf[6]/16;
    accum *= 10;
    accum += buf[6]%16;
    accum *= 10;
    accum += buf[7]/16;
    accum *= 10;
    accum += buf[7]%16;
    accum *= 10;
    accum += buf[8]/16;
    accum *= 10;
    accum += buf[8]%16;
```
Декодирование данных производительности: используется 2 старших байта. Результат возвращается в бинарном виде little endian формате целого числа равного производительности умноженной на 10. Пример кода для декодирования производительности:
```
    uint16_t perf = uint16_t(buf[6])*256+buf[7];
    float performance = perf/10.;
```

Контрольная сумма: 1 байт.

Подсчет контрольной суммы:
```
uint8_t checksum(unsigned char* buf, int cnt) // cnt - к-во переданых байт, buf – массив данных
{
  int i;
  uint8_t s=0;
  for (i = 1; i < cnt; i++) s+=buf[i];
  return s;
}
```
